CREATE TABLE "complications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"watch_id" integer NOT NULL,
	"name" text NOT NULL,
	"rank" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "manufacturers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "manufacturers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"watch_id" integer NOT NULL,
	"source" text NOT NULL,
	"amount_cents" integer NOT NULL,
	"recorded_on" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "watches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"manufacturer_id" integer NOT NULL,
	"model" text NOT NULL,
	"image_url" text,
	"chrono24_url" text
);
--> statement-breakpoint
CREATE UNIQUE INDEX "manufacturers_name_idx" ON "manufacturers" ("name");--> statement-breakpoint
ALTER TABLE "complications" ADD CONSTRAINT "complications_watch_id_watches_id_fkey" FOREIGN KEY ("watch_id") REFERENCES "watches"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "price_points" ADD CONSTRAINT "price_points_watch_id_watches_id_fkey" FOREIGN KEY ("watch_id") REFERENCES "watches"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "watches" ADD CONSTRAINT "watches_manufacturer_id_manufacturers_id_fkey" FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers"("id");